# Generated by Django 6.0.1 on 2026-03-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_alter_voter_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='precinct_number',
            field=models.CharField(max_length=10),
        ),
    ]
