# Generated by Django 6.0.1 on 2026-02-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('profile_image_url', models.URLField(max_length=500)),
                ('bio_text', models.TextField(blank=True)),
                ('join_date', models.DateField()),
            ],
        ),
    ]
