# Generated by Django 6.0.1 on 2026-03-07 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0005_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='mini_insta.profile'),
        ),
    ]
